
package gestiongimnasio.Vistas;

import gestiongimnasio.DAO.SocioDAO;
import gestiongimnasio.Entidades.Socio;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author facun
 */
public class AñadirSocio extends javax.swing.JInternalFrame {
private SocioDAO socioD= new SocioDAO();
private Socio socio=null;
    /**
     * Creates new form AñadirSocio
     */
    public AñadirSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        radiobEstado = new javax.swing.JRadioButton();
        jBañadir = new javax.swing.JButton();
        Jtdni = new javax.swing.JTextField();
        Jtnombre = new javax.swing.JTextField();
        Jtapellido = new javax.swing.JTextField();
        Jtedad = new javax.swing.JTextField();
        Jtcorreo = new javax.swing.JTextField();
        Jttelefono = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGREGAR SOCIOS");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Documento:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado:");

        jBañadir.setBackground(new java.awt.Color(51, 51, 51));
        jBañadir.setForeground(new java.awt.Color(255, 255, 255));
        jBañadir.setText("Añadir Socio");
        jBañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBañadirActionPerformed(evt);
            }
        });

        Jtdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtdniActionPerformed(evt);
            }
        });

        jBbuscar.setText("Buscar por dni");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jBmodificar.setText("Modificar");
        jBmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });

        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar por nombre y apellido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radiobEstado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 199, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 252, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBañadir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBbuscar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Jtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Jtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Jtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(radiobEstado))
                        .addGap(4, 4, 4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBañadir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBañadirActionPerformed
 try {
        int dni = Integer.parseInt(Jtdni.getText());
        String nombre = Jtnombre.getText();
        String apellido = Jtapellido.getText();
        int edad = Integer.parseInt(Jtedad.getText());
        String correo = Jtcorreo.getText();
        String telefono = Jttelefono.getText();
        
        if (nombre.isEmpty() || apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacios");
            return;
        }
        
        Boolean estado = radiobEstado.isSelected();
        
        if (socio == null) {
            socio = new Socio(dni, nombre, apellido, edad, correo, telefono, estado);
            socioD.agregarSocio(socio);
        } else {
            socio.setDni(dni);
            socio.setNombre(nombre);
            socio.setApellido(apellido);
            socio.setEdad(edad);
            socio.setCorreo(correo);
            socio.setTelefono(telefono);
            socio.setEstado(true);
            socioD.agregarSocio(socio);
            socio = new Socio();
        }
        
        limpiarCampos();
    } catch(NumberFormatException nfe) {
        JOptionPane.showMessageDialog(this, "Debe ingresar dni y edad válidos");
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al agregar socio: " + ex.getMessage());
    }
    }//GEN-LAST:event_jBañadirActionPerformed

    private void JtdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtdniActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
            if (socio != null) {
        try {
            int dni = Integer.parseInt(Jtdni.getText());
            String nombre = Jtnombre.getText();
            String apellido = Jtapellido.getText();
            int edad = Integer.parseInt(Jtedad.getText());
            String correo = Jtcorreo.getText();
            String telefono = Jttelefono.getText();
            boolean estado = radiobEstado.isSelected();

            if (nombre.isEmpty() || apellido.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No puede haber campos vacíos");
                return;
            }

            socio.setDni(dni);
            socio.setNombre(nombre);
            socio.setApellido(apellido);
            socio.setEdad(edad);
            socio.setCorreo(correo);
            socio.setTelefono(telefono);
            socio.setEstado(estado);

            boolean actualizacionExitosa = socioD.actualizarSocio(socio);
            if (actualizacionExitosa) {
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Socio actualizado exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el socio.");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Ingrese valores numéricos válidos.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Debe buscar un socio primero.");
    }

    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
    
        
            try {
                if (socio!=null) {
                socioD.eliminarSocio(socio.getId_Socio());
                  socio=null;
                  limpiarCampos();
                  JOptionPane.showMessageDialog(this, "Socio Eliminado");
                  }else{
                     JOptionPane.showMessageDialog(this, "No hay Socio seleccionado");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al borrar socio");
            }
  
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        try{

            int dni=Integer.parseInt(Jtdni.getText());
            socio=socioD.buscarSocioPorDni(dni);

            if (socio!=null) {
               
                Jtnombre.setText(socio.getNombre());
                Jtapellido.setText(socio.getApellido());
                Jtedad.setText(String.valueOf(socio.getEdad()));
                Jtcorreo.setText(socio.getCorreo());
                Jttelefono.setText(socio.getTelefono());

            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Ingrese un Dni valido");
        }
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String nombre = Jtnombre.getText().trim();
    String apellido = Jtapellido.getText().trim();

    if (nombre.isEmpty() || apellido.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese nombre y apellido");
        return;
    }

    try {
        socio = socioD. buscarSocioPorNombreApellido(nombre, apellido);
        if (socio != null) {
            Jtdni.setText(String.valueOf(socio.getDni()));
            Jtedad.setText(String.valueOf(socio.getEdad()));
            Jtcorreo.setText(socio.getCorreo());
            Jttelefono.setText(socio.getTelefono());
            // Assuming you have a JTextField for DNI, uncomment the next line
            // Jtdni.setText(String.valueOf(socio.getDni()));
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún socio con ese nombre y apellido");
            limpiarCampos();
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al buscar el socio: " + ex.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

private void limpiarCampos(){
    Jtdni.setText("");
    Jtnombre.setText("");
    Jtapellido.setText("");
    Jtedad.setText("");
    Jtcorreo.setText("");
    Jttelefono.setText("");
    radiobEstado.setSelected(true);
   
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jtapellido;
    private javax.swing.JTextField Jtcorreo;
    private javax.swing.JTextField Jtdni;
    private javax.swing.JTextField Jtedad;
    private javax.swing.JTextField Jtnombre;
    private javax.swing.JTextField Jttelefono;
    private javax.swing.JButton jBañadir;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton radiobEstado;
    // End of variables declaration//GEN-END:variables
}
