package gestiongimnasio.Vistas;

import gestiongimnasio.DAO.AsistenciaData;
import gestiongimnasio.DAO.ClaseData;
import gestiongimnasio.DAO.MembresiaData;
import gestiongimnasio.Entidades.Asistencia;
import gestiongimnasio.Entidades.Clase;
import gestiongimnasio.Entidades.Membresia;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class Concurrencia extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;

    /**
     * Creates new form Concurrencia
     */
    public Concurrencia() {
        initComponents();
        mostrarFechaActual();
        configurarTabla();
    }

    private void cargarAsistencias(int idSocio) {
        AsistenciaData asistenciaData = new AsistenciaData();
        List<Asistencia> asistencias = asistenciaData.obtenerAsistenciasPorIdSocio(idSocio);

        modeloTabla.setRowCount(0); // Limpiar la tabla

        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy");
        for (Asistencia asistencia : asistencias) {
            Object[] fila = new Object[2];
            fila[0] = sdf.format(asistencia.getFechaAsistencia());
            fila[1] = "Presente"; // Asumimos que todas las asistencias registradas son "Presente"
            modeloTabla.addRow(fila);
        }
    }

    private void configurarTabla() {
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Asistencia");
        jTable1.setModel(modeloTabla);
    }

    private void agregarAsistenciaATabla(java.util.Date fecha, boolean presente) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy");
        String estadoAsistencia = presente ? "Presente" : "Ausente";
        modeloTabla.addRow(new Object[]{sdf.format(fecha), estadoAsistencia});
    }

    private void mostrarFechaActual() {
        // Obtener la fecha actual
        java.util.Date fechaActual = new java.util.Date();

        // Formatear la fecha
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy");
        String fechaFormateada = sdf.format(fechaActual);

        // Establecer el texto del JTextField con la fecha formateada
        FEchaDhoy.setText(fechaFormateada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        claseLabel1 = new javax.swing.JLabel();
        FEchaDhoy = new javax.swing.JTextField();
        nombreDelsocio = new javax.swing.JTextField();
        Prenteboton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FinDeMem = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        claseLabel1.setText("clase");
        jPanel1.add(claseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, 30));

        FEchaDhoy.setText("Fecha Actual");
        FEchaDhoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEchaDhoyActionPerformed(evt);
            }
        });
        jPanel1.add(FEchaDhoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));

        nombreDelsocio.setText("Nombre de socio");
        nombreDelsocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreDelsocioActionPerformed(evt);
            }
        });
        jPanel1.add(nombreDelsocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        Prenteboton.setText("Dar presente");
        Prenteboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrentebotonActionPerformed(evt);
            }
        });
        jPanel1.add(Prenteboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 470, 322));

        FinDeMem.setText("Fin de memebresia");
        FinDeMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinDeMemActionPerformed(evt);
            }
        });
        jPanel1.add(FinDeMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FEchaDhoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEchaDhoyActionPerformed

    }//GEN-LAST:event_FEchaDhoyActionPerformed

    private void nombreDelsocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreDelsocioActionPerformed
        // Llama al método que busca y muestra el fin de la membresía
        mostrarFinDeMembresia();
    }//GEN-LAST:event_nombreDelsocioActionPerformed
    private void mostrarFinDeMembresia() {
        // Obtener el nombre del socio ingresado en nombreDelsocio
        String nombreSocio = nombreDelsocio.getText();

        // Crear una instancia de MembresiaData para obtener la membresía del socio
        MembresiaData membresiaData = new MembresiaData();
        Membresia membresia = membresiaData.obtenerMembresiaActivaPorNombre(nombreSocio);

        // Verificar si se encontró la membresía
        if (membresia != null) {
            // Obtener la fecha de fin de membresía como java.util.Date
            java.util.Date fechaFin = membresia.getFechaFin();

            // Formatear la fecha
            SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM yyyy");
            String fechaFinFormateada = sdf.format(fechaFin);

            // Mostrar la fecha de fin de membresía en FinDeMem
            FinDeMem.setText(fechaFinFormateada);
        } else {
            // Si no se encontró el socio o la membresía, mostrar un mensaje
            FinDeMem.setText("No se encontró la membresía activa.");
        }
    }
    private void PrentebotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrentebotonActionPerformed
        // Obtener el nombre del socio ingresado
    String nombreSocio = nombreDelsocio.getText();

    // Crear una instancia de MembresiaData para obtener la membresía del socio
    MembresiaData membresiaData = new MembresiaData();
    Membresia membresia = membresiaData.obtenerMembresiaActivaPorNombre(nombreSocio);

    if (membresia != null) {
        // Obtener el ID del socio
        int idSocio = membresia.getSocio().getId_Socio();
        
        // Obtener la clase actual (aquí podrías usar obtenerClaseActual(membresia) si es necesario)
        Clase claseActual = obtenerClaseActual(membresia);

        if (claseActual != null) {
            int idClase = claseActual.getId_clase();
            claseLabel1.setText(claseActual.getNombre()); // Mostrar el nombre de la clase en la interfaz

            // Registrar asistencia del día actual
            AsistenciaData asistenciaData = new AsistenciaData();
            asistenciaData.registrarAsistencia(idSocio, idClase, new java.sql.Date(new java.util.Date().getTime()));

            // Cargar todas las asistencias del socio, incluyendo la asistencia recién registrada
            cargarAsistencias(idSocio);
        } else {
            claseLabel1.setText("Clase no encontrada");
            JOptionPane.showMessageDialog(this, "No se encontró una clase asociada para la membresía del socio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró una membresía activa para el socio.");
    }
    }//GEN-LAST:event_PrentebotonActionPerformed
// Definición del método obtenerClaseActual

    private Clase obtenerClaseActual() {
        ClaseData claseData = new ClaseData();
        int idSocio = membresia.getSocio().getId_Socio();
        // Implementa la lógica para obtener la clase actual
        // Por ejemplo, podrías abrir un cuadro de diálogo para que el usuario seleccione una clase

        // Ejemplo  de lógica
        // return new Clase(22, "Yoga", new Entrenador(), "18:00", 20, true);
        // Placeholder: Deberías retornar la clase seleccionada o deducida
        Clase claseActual = claseData.obtenerClasePorMembresia(membresia.getId_membresia());
        return claseActual;
    }
    private void FinDeMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinDeMemActionPerformed

    }//GEN-LAST:event_FinDeMemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FEchaDhoy;
    private javax.swing.JTextField FinDeMem;
    private javax.swing.JButton Prenteboton;
    private javax.swing.JLabel claseLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombreDelsocio;
    // End of variables declaration//GEN-END:variables
}
